ALTER TYPE "IntegrationEntityType" ADD VALUE IF NOT EXISTS 'ATTENDANCE';

ALTER TABLE "StudentSnapshot"
  ADD COLUMN IF NOT EXISTS "attendancePossibleCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "attendancePresentCount" INTEGER NOT NULL DEFAULT 0;
