ALTER TABLE "Subject" ADD COLUMN "stages" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Subject" ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Subject" ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0;
