-- Remove deprecated legacy SignalKey enum values. Postgres has no direct
-- "DROP VALUE" for enums, so recreate the type without them and repoint the
-- one column that uses it. Any Insight row still pointing at a removed value
-- is dropped first so the type swap below can't fail on it.
DELETE FROM "Insight" WHERE "signalKey"::text IN (
  'COLD_CALL_DENSITY',
  'LANGUAGE_PRECISION',
  'LIVE_ADJUSTMENT',
  'RETRIEVAL_PRESENCE',
  'STRETCH_DEPLOYMENT',
  'INDEPENDENT_ACCOUNTABILITY',
  'ERROR_CORRECTION_DEPTH',
  'PARTICIPATION_EQUITY'
);

ALTER TYPE "SignalKey" RENAME TO "SignalKey_old";

CREATE TYPE "SignalKey" AS ENUM (
  'BEHAVIOUR_CLIMATE',
  'PACE_MOMENTUM',
  'ENTRY_ROUTINE',
  'RETRIEVAL_TASK_QUALITY',
  'RETRIEVAL_CHECK',
  'EXPLANATION_CLARITY',
  'MODELLING_EXPLICITNESS',
  'VOCABULARY_PRECISION',
  'DIRECTED_QUESTIONING',
  'STRETCH_IN_ROOM',
  'CFU_CYCLES',
  'RESPONSIVE_ADJUSTMENT',
  'ERROR_CORRECTION_PRECISION',
  'MODELLING_ON_DEMAND',
  'PARTICIPATION_EQUITY_GP',
  'TASK_CLARITY',
  'INDEPENDENT_ACCOUNTABILITY_IP',
  'CIRCULATION_FEEDBACK',
  'STRETCH_DEPLOYMENT_IP',
  'SILENCE_AND_FOCUS',
  'PRESENTATION_STANDARD',
  'WORK_COMPLETION',
  'SUSTAINED_EFFORT',
  'TASK_APPROPRIATENESS',
  'VOLUME_OF_WORK',
  'PRIMARY_BEHAVIOUR_CLIMATE',
  'PRIMARY_PACE_MOMENTUM',
  'PRIMARY_ENTRY_ROUTINE',
  'PRIMARY_RETRIEVAL_TASK_QUALITY',
  'PRIMARY_RETRIEVAL_CHECK',
  'PRIMARY_EXPLANATION_CLARITY',
  'PRIMARY_MODELLING_EXPLICITNESS',
  'PRIMARY_PHONICS_VOCABULARY_PRECISION',
  'PRIMARY_DIRECTED_QUESTIONING',
  'PRIMARY_STRETCH_IN_ROOM',
  'PRIMARY_CFU_CYCLES',
  'PRIMARY_RESPONSIVE_ADJUSTMENT',
  'PRIMARY_ERROR_CORRECTION_PRECISION',
  'PRIMARY_ORACY_GUIDED',
  'PRIMARY_PARTICIPATION_EQUITY',
  'PRIMARY_TASK_CLARITY',
  'PRIMARY_INDEPENDENT_ACCOUNTABILITY',
  'PRIMARY_CIRCULATION_FEEDBACK',
  'PRIMARY_STRETCH_DEPLOYMENT',
  'PRIMARY_ORACY_INDEPENDENT'
);

-- AlterTable: repoint Insight.signalKey at the new enum type.
ALTER TABLE "Insight" ALTER COLUMN "signalKey" TYPE "SignalKey" USING ("signalKey"::text::"SignalKey");

DROP TYPE "SignalKey_old";

-- Drop tenant signal-label rows for the removed legacy keys (TenantSignalLabel.signalKey is a
-- free-text column, so it isn't affected by the enum change above, but these rows are now orphaned).
DELETE FROM "TenantSignalLabel" WHERE "signalKey" IN (
  'COLD_CALL_DENSITY',
  'LANGUAGE_PRECISION',
  'LIVE_ADJUSTMENT',
  'RETRIEVAL_PRESENCE',
  'STRETCH_DEPLOYMENT',
  'INDEPENDENT_ACCOUNTABILITY',
  'ERROR_CORRECTION_DEPTH',
  'PARTICIPATION_EQUITY'
);
