-- CreateEnum
CREATE TYPE "SchoolType" AS ENUM ('PRIMARY', 'SECONDARY');

-- AlterTable
ALTER TABLE "TenantSettings" ADD COLUMN "schoolType" "SchoolType" NOT NULL DEFAULT 'SECONDARY';

-- Add FK from TenantSettings to Tenant (Prisma schema relation)
ALTER TABLE "TenantSettings" ADD CONSTRAINT "TenantSettings_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AlterEnum SignalKey: add new values (PostgreSQL requires one ALTER per new enum value)
ALTER TYPE "SignalKey" ADD VALUE 'ENTRY_ROUTINE';
ALTER TYPE "SignalKey" ADD VALUE 'RETRIEVAL_TASK_QUALITY';
ALTER TYPE "SignalKey" ADD VALUE 'RETRIEVAL_CHECK';
ALTER TYPE "SignalKey" ADD VALUE 'EXPLANATION_CLARITY';
ALTER TYPE "SignalKey" ADD VALUE 'VOCABULARY_PRECISION';
ALTER TYPE "SignalKey" ADD VALUE 'DIRECTED_QUESTIONING';
ALTER TYPE "SignalKey" ADD VALUE 'STRETCH_IN_ROOM';
ALTER TYPE "SignalKey" ADD VALUE 'RESPONSIVE_ADJUSTMENT';
ALTER TYPE "SignalKey" ADD VALUE 'ERROR_CORRECTION_PRECISION';
ALTER TYPE "SignalKey" ADD VALUE 'MODELLING_ON_DEMAND';
ALTER TYPE "SignalKey" ADD VALUE 'PARTICIPATION_EQUITY_GP';
ALTER TYPE "SignalKey" ADD VALUE 'TASK_CLARITY';
ALTER TYPE "SignalKey" ADD VALUE 'INDEPENDENT_ACCOUNTABILITY_IP';
ALTER TYPE "SignalKey" ADD VALUE 'CIRCULATION_FEEDBACK';
ALTER TYPE "SignalKey" ADD VALUE 'STRETCH_DEPLOYMENT_IP';
ALTER TYPE "SignalKey" ADD VALUE 'SILENCE_AND_FOCUS';
ALTER TYPE "SignalKey" ADD VALUE 'PRESENTATION_STANDARD';
ALTER TYPE "SignalKey" ADD VALUE 'WORK_COMPLETION';
ALTER TYPE "SignalKey" ADD VALUE 'SUSTAINED_EFFORT';
ALTER TYPE "SignalKey" ADD VALUE 'TASK_APPROPRIATENESS';
ALTER TYPE "SignalKey" ADD VALUE 'VOLUME_OF_WORK';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_BEHAVIOUR_CLIMATE';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_PACE_MOMENTUM';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_ENTRY_ROUTINE';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_RETRIEVAL_TASK_QUALITY';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_RETRIEVAL_CHECK';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_EXPLANATION_CLARITY';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_MODELLING_EXPLICITNESS';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_PHONICS_VOCABULARY_PRECISION';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_DIRECTED_QUESTIONING';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_STRETCH_IN_ROOM';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_CFU_CYCLES';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_RESPONSIVE_ADJUSTMENT';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_ERROR_CORRECTION_PRECISION';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_ORACY_GUIDED';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_PARTICIPATION_EQUITY';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_TASK_CLARITY';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_INDEPENDENT_ACCOUNTABILITY';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_CIRCULATION_FEEDBACK';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_STRETCH_DEPLOYMENT';
ALTER TYPE "SignalKey" ADD VALUE 'PRIMARY_ORACY_INDEPENDENT';
